apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: GraphQLGameServer
  annotations:
    github.com/project-slug: Andrewpk/GraphQLGameServer
spec:
  type: other
  lifecycle: unknown
  owner: Customer-Integrations
